language: smalltalk
sudo: false

os:
  - linux

addons:
  ssh_known_hosts: ccmi.fit.cvut.cz

env:
  global:
    - ARTIFACT_DIR=openponk-borm-image-$TRAVIS_BUILD_NUMBER

smalltalk:
  - Pharo32-7.0
  - Pharo64-7.0
  - Pharo64-8.0

cache:
  directories:
    - $SMALLTALK_CI_BUILD_BASE/pharo-local/package-cache

before_install:
  - source ./scripts/ssh.sh

after_success:
  - scp -p ${SMALLTALK_CI_BUILD}/coveralls_results.json "openponk@ccmi.fit.cvut.cz:~/www/metrics/borm-editor/coveralls/${TRAVIS_BUILD_NUMBER}.json"
  - ./scripts/copy-image.sh $SMALLTALK_CI_IMAGE $ARTIFACT_DIR/openponk
  - ./scripts/mark-image.sh $ARTIFACT_DIR/openponk

deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh
  - provider: script
    on:
      tags: true
    skip_cleanup: true
    script: scripts/deploy.sh

notifications:
  email: false
  slack:
    secure: A7TM72JfKVhcAdkFT2tQH+LdB3RNcr9UyPShT7e8hM3RpD0uL4ZjR5vz8lKRlmjYIo4lbThSO8E1U+BZ5dc7Wg28RwBYP6tvdTJXsL54yaWGuq4uccxw8+zEoLD06XR6UAfiee8wplittCC/jIm6Opb1xHpcXh7RAn6rEA6ztAQWxVmECmKnmVU9a3Fhj/9ZSVHVBb8atv3tbHEVTvkNzYuBRq08NRHYY3GvEWXwdYqqiP4VU1yuGxYUed+vPwUfywSK45vcVSmbmXS3OrlOWXyC4LEgl0cuObEL4r1J6GUji0955XYXYIdo4zTMWwcEpoohOQLQ9FTzUydH4c4ZW9Luzp1qkktNTSyAU0NM8CFyimYovzSXahnwD0yypN465NQorm5C9lpD/+0RXlNr4MhukV1O6jSJAjKufI2z6EGr4SYYIoA7qt7tLXHIH72ZxmVStHpjaxnjl4+WwBkOvTlSPEiSHtCyhPFGaoMlXLZeKus190JjPPeVeUKAny4xaeHDY6HIB3/R0cUcDyWWzTWRmAHrmKnHD+WWywVyjBtYR5uvGQQmP/nt0kRm9yj9hFQsHjR6/M72Cizx1NwZMRacjdfA7gVOkjprHFR/e7zp0sqhdai00GTFmvJjAz6dA99Ns71z+gVbSJgT1AZYA88RYrkXyb97kfL2HZbGrlc=
