language: smalltalk
sudo: false
addons:
    apt:
        packages:
            - libssl1.0.0:i386
            - libcairo2:i386
smalltalk:
    - Pharo-5.0
env:
    global:
        - BASELINE="BormEditor"
        - TESTS="Borm.*"
        - PACKAGES="/repository"
        - BASELINE_GROUP="default"
