Class {
	#name : 'OPBormCommunicationSimulator',
	#superclass : 'OPEdgeSimulator',
	#category : 'OpenPonk-BormSimulation-Simulation',
	#package : 'OpenPonk-BormSimulation',
	#tag : 'Simulation'
}

{ #category : 'testing' }
OPBormCommunicationSimulator >> handleFire [
]

{ #category : 'testing' }
OPBormCommunicationSimulator >> isSimulable [

	^ false
]

{ #category : 'testing' }
OPBormCommunicationSimulator >> isSteppable [

	^ false
]
